# -*- coding: utf-8 -*-
"""Cópia de 1.0- Análise de Dados - Tomada de Decisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qo85TnY2yINjvckfxLHp6nc3qxSdwV1Z

---

<h1 align=left><font size = 8, style="color:rgb(200,0,0)"><b>Análise de Dados - Tomada de Decisão </b></font></h1>

---

### **Questionário: A Importância da Análise de Dados na Tomada de Decisões**

1. **Por que a análise de dados é crucial na tomada de decisões em uma organização?**
   - A) Ajuda a tomar decisões baseadas em intuição.
   - B) Fornece insights baseados em evidências e dados objetivos.
   - C) Garante que todas as decisões sejam rápidas.
   - D) Substitui a necessidade de experiência no setor.
"""

**B) Fornece insights baseados em evidências e dados objetivos.**



"""
2. **Como Python pode ser utilizado para análise de dados?**
   - A) Apenas para criação de sites.
   - B) Como uma linguagem de script para automatizar tarefas de análise.
   - C) Apenas para desenvolvimento de jogos.
   - D) Para editar imagens e vídeos.
"""

B) Como uma linguagem de script para automatizar tarefas de análise.

"""
3. **Qual das bibliotecas a seguir é mais comumente usada em Python para análise de dados?**
   - A) TensorFlow
   - B) Pandas
   - C) Flask
   - D) Matplotlib

"""

B) Pandas

"""4. **Como o Google Colab facilita o processo de análise de dados?**
   - A) Permitindo a execução de código Python em um ambiente baseado na nuvem sem configuração local.
   - B) Fornecendo templates de apresentações prontas.
   - C) Garantindo anonimato total em todas as análises.
   - D) Fazendo backup automático de todos os dados analisados.

"""

R - A) Permitindo a execução de código Python em um ambiente baseado na nuvem sem configuração local.

"""
5. **Qual é o papel da visualização de dados na tomada de decisões?**
   - A) Apenas embelezar relatórios.
   - B) Simplificar a interpretação de dados complexos.
   - C) Reduzir a precisão dos dados.
   - D) Proteger os dados contra perda.
"""

R- B) Simplificar a interpretação de dados complexos.

"""
6. **Qual ferramenta em Python é amplamente usada para criar gráficos e visualizações que auxiliam na tomada de decisões?**
   - A) Scikit-learn
   - B) Matplotlib
   - C) Beautiful Soup
   - D) Django
"""

R- B) Matplotlib

"""
7. **Como a análise preditiva pode influenciar a tomada de decisões em uma empresa?**
   - A) Ela elimina completamente a necessidade de análise histórica.
   - B) Ajuda a prever resultados futuros e a planejar estratégias.
   - C) Substitui a necessidade de análise de dados em tempo real.
   - D) Aumenta o risco de decisões equivocadas.
"""

R- B) Ajuda a prever resultados futuros e a planejar estratégias.

"""
8. **Por que a integração do Python com bibliotecas como Pandas e NumPy é importante na análise de dados?**
   - A) Apenas para desenvolvedores web.
   - B) Facilita a manipulação e análise eficiente de grandes conjuntos de dados.
   - C) Só é útil em aplicativos móveis.
   - D) Serve para melhorar a qualidade da imagem.

"""

R- B) Facilita a manipulação e análise eficiente de grandes conjuntos de dados.
]

"""9. **De que maneira o Google Colab permite uma análise colaborativa de dados?**
   - A) Permitindo que vários usuários compartilhem e editem o mesmo notebook em tempo real.
   - B) Limitando o acesso aos notebooks para um único usuário.
   - C) Fazendo backup dos dados diretamente em um dispositivo externo.
   - D) Fornecendo gráficos prontos para uso em relatórios.

"""

R- A) Permitindo que vários usuários compartilhem e editem o mesmo notebook em tempo real.

"""
10. **Como o uso de Python em ambientes como o Google Colab pode impactar a agilidade na tomada de decisões?**
    - A) Tornando o processo de análise mais lento e burocrático.
    - B) Facilitando a experimentação rápida e a prototipagem de modelos de dados.
    - C) Aumentando a necessidade de hardware especializado.
    - D) Garantindo que apenas uma pessoa tenha acesso aos resultados."""

R- B) Facilitando a experimentação rápida e a prototipagem de modelos de dados.